### ISSUE TITLE
Incorrect hit count on some rules

### ISSUE THREAD

**Issue by KevSex** [ServerCentral/praeco#133]
I have two rules set up in the same way (duplicated one and changed a couple of parameters)

site1-Heartbeat
```
__praeco_full_path: Heartbeat/site1-Heartbeat
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"tags","selectedOperator":"contains","selectedOperand":"tags","value":"site1"}}]}}
alert:
  - email
alert_subject: 'ALERT: No data received from site1'
alert_subject_args: []
alert_text: >
  I've not seen any data come in from site1. Verify connectivity
  status
alert_text_args: []
alert_text_type: alert_text_only
doc_type: doc
email:
  - me@mail.com
filter:
  - query:
      query_string:
        query: 'tags:site1'
from_addr: praeco@mail.com
import: ../BaseRule.config
index: ciscoasa-*
is_enabled: true
name: site1-Heartbeat
realert:
  days: 1
terms_size: 50
threshold: 1
timeframe:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: iso
type: flatline
use_count_query: true
use_strftime_index: false
```

site2-Heartbeat
```
__praeco_full_path: Heartbeat/site2-Heartbeat
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"tags","selectedOperator":"contains","selectedOperand":"tags","value":"site2"}}]}}
alert:
  - email
alert_subject: 'ALERT: No data received from site2'
alert_subject_args: []
alert_text: >
  I've not seen any data come in from site2. Verify connectivity
  status
alert_text_args: []
alert_text_type: alert_text_only
doc_type: doc
email:
  - me@mail.com
filter:
  - query:
      query_string:
        query: 'tags:site2'
from_addr: praeco@mail.com
import: ../BaseRule.config
index: ciscoasa-*
is_enabled: true
name: site2-Heartbeat
realert:
  days: 1
terms_size: 50
threshold: 1
timeframe:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: iso
type: flatline
use_count_query: true
use_strftime_index: false
```

These are to alert me when it doesn't see any data from a specific site in a 5 minute period.
The problem I'm seeing is that one works and the other doesn't.

For the one that's working, I'm seeing hits under the 'Query Log' with 0 matches (as expected) however the one that isn't working shows 0 hits and >1 matches (even though its seeing the data in the 'Overview' tab). What I do find weird is the number of matches is either 2 or 4 for some reason (not sure if random or has anything to do with this behaviour).

In total, I have 7 of these rules, 4 appear to work as expected, the other 3 are having this issue.
I've updated to the latest version (0.3.6) and still experiencing this.

Any ideas?
