### ISSUE TITLE
Blank rule after applying manual filter to new term alert

### ISSUE THREAD

**Issue by scott-oit** [ServerCentral/praeco#187]
If I create a new rule with the New Term event and apply a manual filter, I am not able to edit the rule after saving. If I select the rule in Praeco, I get a blank screen. The YAML looks fine. I used a simple rule in the "field : value" format.

As a work around, use the Builder. However, you are not able to use OR statements.

**Comment by daichi703n** [comment]
Editing the rule directly is deprecated.

For OR rule, doesn't it work like this?

![image](https://user-images.githubusercontent.com/22485636/75209831-aadb6b80-57c2-11ea-8028-aabdaaaa3611.png)

Generated YAML:

```
__praeco_full_path: monitoring-elk/test.new_term
__praeco_query_builder: >-
  {"query":{"logicalOperator":"any","children":[{"type":"query-builder-rule","query":{"rule":"host","selectedOperator":"contains","selectedOperand":"host","value":"test"}},{"type":"query-builder-rule","query":{"rule":"error_message","selectedOperator":"contains","selectedOperand":"error_message","value":"fatal"}}]}}
alert:
  - slack
alert_on_missing_field: false
alert_subject: New Term Found
alert_subject_args: []
filter:
  - query_string:
      query: 'host:test OR error_message:fatal'
import: ../BaseRule.config
...
```

**Comment by scott-oit** [comment]
Using the manual filter breaks the UI for me. Using the Builder only works just fine.
By editing the rule, do you mean by editing YAML file? If so, I didn't do that. Only viewed it.
Here is my yaml if that's helpful:

```yaml
aggregation:
  schedule: 10 * * * *
aggregation_key: server.ip
alert:
  - email
alert_on_missing_field: false
alert_subject: "Port {0}\_open on {1}\_({2})"
alert_subject_args:
  - server.port
  - server.domain
  - server.ip
alert_text_type: alert_text_only
email:
  - email@address.com
filter:
  - query_string:
      query: >-
        nmap.port.state: open AND network.name : Management OR network.name :
        Server OR network.name : Printer OR network.name : Voice
from_addr: email@address.com
import: ../../BaseRule.config
index: nmap-*
is_enabled: true
name: NMAP New Port
query_key: nmap.fingerpint.keyword
realert:
  minutes: 0
summary_table_fields:
  - server.ip
  - server.domain
  - server.port
terms_window_size:
  days: 30
timestamp_field: '@timestamp'
timestamp_type: iso
type: new_term
use_keyword_postfix: true
use_strftime_index: false
window_step_size:
  days: 1
```

![image](https://user-images.githubusercontent.com/45404878/75210693-a5d0da80-5736-11ea-80d5-e7fa29fc48a0.png)

**Comment by daichi703n** [comment]
I see. I reproduced your issue.

I think this is a bug on generating new_term rule. I'm continue to specify where is the bug happen. (Praeco? ElastAlert Server?)

By my testing, generated rule.yml has invalid syntax about filter.

```
$ cat test.new_term.yaml
...
filter:
  - query_string:
      query: 'host:tets'
import: ../BaseRule.config
...
```

This should be

```
...
filter:
  - query:
      query_string:
        query: 'host:tets'
import: ../BaseRule.config
...
```

(debugging only, **not workaround**)
Modifying rule.yaml on Server fixes the displaying on GUI. Therefore, the root cause of this issue is seems to be correct.

(**workaround**) By using Builder, 

```
__praeco_query_builder: '{"query":{"logicalOperator":"all","children":[]}}'
```

is added into rule.yml, and skip the `filter:` section on loading, this will not break the GUI.
