### ISSUE TITLE
Alerts working when rules manually modified, but getting date field parsing errors in UI

### ISSUE THREAD

**Issue by shortstack** [ServerCentral/praeco#200]
Running Praeco from docker-compose setup
Pointing at ES 6.5.4 backend which is behind Graylog

I had to add the following timestamp fields to the rule file manually on the praeco server
```
timestamp_type: custom
timestamp_format: '%Y-%m-%d %H:%M:%S.%f'
timestamp_format_expr: 'ts[:23] + ts[26:]'
```
When I remove them (and allow it to use iso/default format), the UI works fine, but the alerting and elastalert do not. 
When added, it's the other way around. The UI complains about date field parsing but the rules/alerts work as expected. 

## Rule file
```
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"event_id","selectedOperator":"contains","selectedOperand":"event_id","value":"4625"}}]}}
alert:
  - slack
alert_subject: 'Failed logons on {0}'
alert_subject_args:
  - source
doc_type: message
filter:
  - query:
      query_string:
        query: 'event_id:4625'
import: BaseRule.config
index: graylog_*
is_enabled: true
name: Failed logons
num_events: 1
realert:
  minutes: 5
slack_channel_override: '#ndr-alerts'
slack_emoji_override: ':rotating_light:'
slack_msg_color: danger
slack_title_link: 'http://localhost:8080/rules/Failed%20logons'
slack_username_override: Praeco
terms_size: 50
timeframe:
  minutes: 10
timestamp_field: timestamp
timestamp_type: custom
timestamp_format: '%Y-%m-%d %H:%M:%S.%f'
timestamp_format_expr: 'ts[:23] + ts[26:]'
type: frequency
use_strftime_index: false
```

## Getting the following in the UI:
<img width="1917" alt="Screenshot 2020-04-24 10 24 42" src="https://user-images.githubusercontent.com/1244979/80223462-5283e700-8616-11ea-8a39-d1aacd4f1fd9.png">

<img width="1557" alt="Screenshot 2020-04-24 10 26 02" src="https://user-images.githubusercontent.com/1244979/80223488-59aaf500-8616-11ea-90cb-5b6b2ed591fb.png">

## But alerts and elastalert.test_rule work
<img width="1919" alt="Screenshot 2020-04-24 10 24 52" src="https://user-images.githubusercontent.com/1244979/80223577-77785a00-8616-11ea-8fa7-afe3d553bc1c.png">
<img width="1619" alt="Screenshot 2020-04-24 10 25 33" src="https://user-images.githubusercontent.com/1244979/80223594-7a734a80-8616-11ea-986c-ad9071e1f831.png">
