### ISSUE TITLE
Alerts mails are being sent in base64?

### ISSUE THREAD

**Issue by ifmusic** [ServerCentral/praeco#92]
Hi! First of, ... Great UI for Elastalert!, this may be a key tool for our infrastructure monitoring.
I'm trying to migrate my existing native Elastalert alerts to this tool (the YAML format doesn't seem to be directly compatible (?))
I created some test alerts and everything seemed fine but when I received an Email for a test alert, the encoding was weird; the email's body seems base64. 

Like so..:
![image](https://user-images.githubusercontent.com/919625/52759540-ff161200-2fea-11e9-963e-1264fceef9d9.png)
This is the Email preview:
![image](https://user-images.githubusercontent.com/919625/52759595-3684be80-2feb-11e9-8be9-8bad011bf4fe.png)

I'm on Ubuntu 16.04 LTS with docker.
Any ideas?
Thanks so much and keep it up!

**Comment by johnsusek** [comment]
Unfortunately praeco was not designed to parse elastalert rules written outside of praeco. Your best best is to create new rules and copy/paste in the alert text. The reason is because parsing the elastalert `filter` option from text into GUI is extremely difficult. Praeco does not support all elastalert `filter` types, only a subset. Sorry about this limitation.

Regarding this issue with the alert text, can you share what your rule .yaml file looks like?

Thanks

**Comment by ifmusic** [comment]
Sure! 
Here's an example YAML :

```
__praeco_full_path: Mgmt/MGMT_DuplicateIPs
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"switch-message","selectedOperator":"contains","selectedOperand":"switch-message","value":"\"address
  conflict\""}}]}}
alert:
  - email
alert_subject: |
  Alerta de IPs Duplicadas
alert_subject_args: []
alert_text: |
  {0}
alert_text_args:
  - switch-message
alert_text_type: alert_text_only
email: rjimenez@boletinoficial.gob.ar
filter:
  - query:
      query_string:
        query: 'switch\-message:"address conflict"'
from_addr: elastalert_servecentral@boletinoficial.gob.ar
import: ../BaseRule.config
index: logstash-switches-*
is_enabled: true
name: MGMT_DuplicateIPs
realert:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: iso
type: any
use_strftime_index: false
```
Thanks!

**Comment by johnsusek** [comment]
@ifmusic It looks like praeco is generating the correct rule file here. I am not sure why elastalert is creating the alert_text like that. You might want to check with https://github.com/Yelp/elastalert and see if there is any troubleshooting or help you can get from that repo. Praeco just generates the rule .yaml files, but doesn't really control the sending of the email to you. This might have something to do with unicode/utf-8/character encoding in elastalert codebase, but that is just a guess.

**Comment by ifmusic** [comment]
Thanks for the answer!, Just to add some more info I found interesting.
I removed all email options from the YAML of the alert files:
```
__praeco_full_path: Logins fallido en HP ILOs
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"message","selectedOperator":"contains","selectedOperand":"message","value":"\"Login
  failure\""}}]}}
alert:
  - email
email: *****
filter:
  - query:
      query_string:
        query: 'message:"Login failure"'
import: BaseRule.config
index: logstash-serverilos-*
is_enabled: true
name: Logins fallido en HP ILOs
realert:
  minutes: 1
timestamp_field: '@timestamp'
timestamp_type: iso
type: any
use_strftime_index: false
```

With this config, the email's body contains the "message" field just fine.
Thanks!
